[package]
name = "examine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.9"
serde = { version = "1.0.183", features = ["derive"] }
tonic = "0.9.2"
